# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-19 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_premiumproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PremiumProject',
        ),
    ]
