# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-12 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account',
            field=models.CharField(default='free', max_length=40),
        ),
    ]
