# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
