# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-08 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='img/tasks'),
        ),
    ]
